Repository FRONTENDSCHOOL8/market-emong, pull requests merged in 2024-01, with the labels that each got.

#24 main페이지 제일 위에 광고 스와이퍼 및 유튜브 광고 포함 및 팝업창 구현 완료.
  index.html
  main-advertising.js
  src/assets/popup.png
  src/styles/tailwind.css
  tailwind.config.js
Labels: ✂ Modify, ✨ Feature, 🪓markup, 🥈 importance: 2nd

#27 공통컴포넌트 header, footer 마크업
  index.html
  public/components/footer.html
  public/components/header.html
  public/logo-emong.png
  src/assets/ic-blog.png
  src/assets/ic-cart.svg
  src/assets/ic-character.png
  src/assets/ic-down.svg
  src/assets/ic-facebook.png
  src/assets/ic-gift.png
  src/assets/ic-hamburger.png
  src/assets/ic-heart.svg
  src/assets/ic-instagram.png
  src/assets/ic-location.svg
  src/assets/ic-logo-isms.png
  src/assets/ic-logo-privacy.png
  src/assets/ic-logo-tosspayments.png
  src/assets/ic-logo-wooriBank.png
  src/assets/ic-naverpost.png
  src/assets/ic-search.svg
  src/assets/ic-tool.png
  src/assets/ic-youtube.png
  src/js/header.js
  src/js/include.js
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🥰 Accessibility, ✨ Feature, 🪓markup, 🥇 importance: 1st

#38 비트 컨피그 파일 배포때 에러 수정
  src/assets/question-mark.svg
  src/pages/productList/index.html
  src/pages/productList/productList.js
  vite.config.js
Labels: 🐞BugFix

#49 Main component header&footer 수정
  public/components/footer.html
  public/components/header.html
  src/js/header.js
  src/styles/tailwind.css
Labels: 🥰 Accessibility, ✂ Modify, 🥇 importance: 1st

#54 main 페이지 수정 및 product list 페이지 마크업 및 css완료.
  .gitignore
  index.html
  main.js
  src/assets/ic-arrow.svg
  src/assets/ic-list-reload.svg
  src/pages/productList/index.html
  src/pages/productList/productList.js
  src/styles/tailwind.css
  tailwind.config.js
Labels: 🥰 Accessibility, ✂ Modify, ✨ Feature, 🪓markup, 🥇 importance: 1st

#57 Feature/sign up page
  index.html
  public/assets/ic-is-checked.svg
  public/assets/ic-is-unchecked.svg
  public/components/header.html
  src/assets/signUp-arrow.svg
  src/pages/login/index.html
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
  tailwind.config.js
Labels: 🥰 Accessibility, ✨ Feature, 🪓markup, 🥇 importance: 1st

#59 Feature/detail
  index.html
  main-cProduct-swiper.js
  src/assets/Bell.svg
  src/assets/Heart.svg
  src/assets/detail-circulation.svg
  src/assets/detail-delivery.svg
  src/assets/detail-list-icon.svg
  src/assets/detail-only-e.svg
  src/assets/detail-price.svg
  src/assets/doraemon-detail.png
  src/assets/doraemon.png
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: 🥰 Accessibility, ✨ Feature, 🪓markup, 🥇 importance: 1st

#61 회원가입 javascript 기본동작 구현
  src/components/footer.html
  src/components/header.html
  src/js/include.js
  src/lib/index.js
  src/lib/validation/index.js
  src/lib/validation/validateDay.js
  src/lib/validation/validateEmail.js
  src/lib/validation/validateId.js
  src/lib/validation/validateMonth.js
  src/lib/validation/validatePhone.js
  src/lib/validation/validatePw.js
  src/lib/validation/validateYear.js
  src/pages/login/index.html
  src/pages/productList/productList.js
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
  src/styles/product.css
  vite.config.js
Labels: ✨ Feature, 🥇 importance: 1st

#66 로그인 회원가입 javascript 완료 / 주소 찾기는 아직 없습니다.
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: ✨ Feature, 🥇 importance: 1st

#68 최근 본 상품 / 상품리스트 페이지 수정중.
  index.html
  main.js
  src/assets/current-test.png
  src/components/header.html
  src/components/recently.html
  src/js/include.js
  src/js/recently.js
  src/pages/productList/index.html
  src/pages/productList/productList.js
  tailwind.config.js
Labels: ✂ Modify, ✨ Feature, 🥇 importance: 1st, 🥈 importance: 2nd

#70 광고창 해결 및 comma 함수 넣었습니다~
  index.html
  main.js
  public/assets/product-cart.svg
  src/lib/index.js
  src/lib/util/comma.js
  src/lib/util/index.js
  src/pages/detail/index.html
  src/styles/product.css
Labels: 🐞BugFix

#73 장바구니 페이지 js 기능 수정
  src/components/header.html
  src/lib/error/typeError.js
  src/lib/storage/Storage.js
  src/lib/storage/typeOf.js
  src/pages/cart/cart.js
  src/pages/cart/index.html
  tailwind.config.js
  vite.config.js
Labels: 🥰 Accessibility, ✨ Feature, 🥇 importance: 1st

#75 장바구니 페이지 javascript
  src/pages/cart/cart.js
  vite.config.js
Labels: 🥰 Accessibility, ✨ Feature, 🥇 importance: 1st

#77 최근 본 상품 수정 및 상품 페이지 링크 연결.
  index.html
  main.js
  src/components/recently.html
  src/js/include.js
  src/js/recently.js
  src/pages/productList/index.html
  src/pages/productList/productList.js
  tailwind.config.js
Labels: 🐞BugFix, ✨ Feature, 🥇 importance: 1st

#79 장바구니에 담긴 상품 랜더링
  src/components/footer.html
  src/components/header.html
  src/lib/util/beforeComma.js
  src/lib/util/index.js
  src/pages/cart/cart.js
  src/pages/cart/index.html
Labels: ✂ Modify, 🥇 importance: 1st

#80 detail page js(수량에 따른 금액 증가, 감소 및 장바구니 담기 기능 추가)
  src/js/include.js
  src/pages/detail/detail.js
  src/pages/detail/index.html
  vite.config.js
Labels: ✨ Feature

#81 header image 수정
  src/components/header.html
  src/js/header.js
  src/pages/cart/cart.js
Labels: 🐞BugFix

#84 detail page 상품 후기 및 문의 마크업, css 추가
  public/assets/detail/Bell.svg
  public/assets/detail/Heart.svg
  public/assets/detail/Lock.svg
  public/assets/detail/detail-Minus.svg
  public/assets/detail/detail-Plus.svg
  public/assets/detail/detail-arrow-l.svg
  public/assets/detail/detail-arrow-r.svg
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: 🥰 Accessibility, ✨ Feature
